services:
  php:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./public:/var/www/html

  browsersync:
    image: ustwo/browser-sync:latest
    command: ['start', '--proxy', 'php:8000', '--files', './**/*', '--port', '3000', '--no-open']
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - ./public:/source
    depends_on:
      - php
